### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by olebonn** [andygruber/songseeker-card-generator#4]
My knowledge is very limited so I don't know what is actually not working. 
But trying to run the script (name is generatePlayCards.py not card_generator.py btw), the terminal gives me the following error. 

qr_code_path = f"qr_{hex_dig}.png" # Unique path for each QR code
                                     ^
SyntaxError: invalid syntax

Any help appreciated, lovely project!

**Comment by andygruber** [comment]
Hey, ty for the feedback.

You are absolutely right about the .py filename, gonna correct that, but maybe lets look at the error.

I somehow suspect, that there are other errors or warnings maybe before.

Please can you provide the complete log from the run and the exact command you are calling, as well as the the directory name you are calling it from? Please use the provided `data/example-youtube-songs.csv` for your test.

In addition also add the output from the command `pip list`

**Comment by olebonn** [comment]
During the installation I hat to use pip3 instead of pip to install the required packages, maybe that's the reason for the error? 
pip3 list output: 
Package           Version
----------------- ------------
chardet           5.2.0
mock-open         1.4.0
numpy             1.26.4
pandas            2.2.2
pillow            10.3.0
pip               24.0
pypng             0.20220715.0
python-dateutil   2.9.0.post0
pytz              2024.1
qrcode            7.4.2
reportlab         4.2.0
six               1.16.0
typing_extensions 4.11.0
tzdata            2024.1

I navigate to the directory using the following command
`cd songseeker-card-generator`
and then try the following command:
`python generatePlayCards.py data/example-youtube-songs.csv example.pdf`

This is the result:
songseeker-card-generator ole$ python generatePlayCards.py data/example-youtube.songs.csv example.pdf
  File "generatePlayCards.py", line 27
    qr_code_path = f"qr_{hex_dig}.png" # Unique path for each QR code
                                     ^
SyntaxError: invalid syntax

Thanks for your help!

**Comment by andygruber** [comment]
I now double-checked that whitespaces in paths are no problem, like this:
```
C:\work\songseeker-card-generator - Copy> python generatePlayCards.py data/example-youtube-songs.csv example.pdf
```

Maybe your python version differs, what do you get with `python --version` ?

**Comment by olebonn** [comment]
Thanks, that was the hint. Terminal said I run python version 2.7.16, so I just had to run the command with python3 generatePlayCards.py. 

Hope this information is helpful ;-)
Thank you!
